
table users {
  id int
  fullName varchar 
  email varchar
  isStaff boolean
  userStatId int
}

table posts {
    id int
    userId int
    title varchar
    description varchar
    tickerId int 
    datePosted date
}

table tickers {
    id int
    symbol varchar

}

table userStats {
  id int
  userId int
  tradeLong int
  tradeShort int
  avgTradeDirection decimal
}

table likes {
  id int [primary key]
  userId int  
  postId int  
  likedAt date 
}

table media {
  id int
  userId int
  media varchar
}

table comments {
  id int
  userId int
  postId int
  description varchar
}


Ref: "tickers"."id" < "posts"."tickerId"

Ref: "users"."id" < "posts"."userId"

Ref: "users"."id" < "likes"."userId"

Ref: "posts"."id" < "likes"."postId"

Ref: "users"."id" < "userStats"."userId"

Ref: "users"."id" < "media"."userId"

Ref: "users"."id" < "comments"."userId"

Ref: "posts"."id" < "comments"."postId"